openapi: 3.0.1
info:
  title: Payment Order Initiation
  description: This service domain provides a customer payment service. It captures the payer and payee details and other key properties of the payment and initiates the orchestration of the transaction. It provides support for repeating/scheduled payments.
  contact:
    name: BIAN
    url: https://bian.org
  version: 14.0.0
servers:
  - url: https://virtserver.swaggerhub.com/B154/BIAN/PaymentOrderInitiation/14.0.0
tags:
  - name: CR - PaymentOrderInitiationTransaction
paths:
  /payment-order-initiation/initiate:
    post:
      tags:
        - CR - PaymentOrderInitiationTransaction
      summary: InCR Initiate a payment transaction
      description: InCR Initiate a payment transaction
      operationId: initiate
      requestBody:
        $ref: '#/components/requestBodies/PaymentOrderInitiationTransaction'
      responses:
        '201':
          $ref: '#/components/responses/PaymentOrderInitiationTransaction'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '429':
          $ref: '#/components/responses/TooManyRequests'
        '500':
          $ref: '#/components/responses/InternalServerError'
components:
  schemas:
    ExceptionResponse:
      type: object
      properties:
        message:
          type: string
          description: General error description raised by the system.
          example: Error calling the service
        details:
          type: array
          description: List of details associated with the reported error.
          items:
            $ref: '#/components/schemas/ExceptionDetail'
      description: Standard error structure containing the failure type and associated technical details.
    ExceptionDetail:
      type: object
      properties:
        code:
          type: string
          description: Specific provider or component error code.
          example: CODE0001
        description:
          type: string
          description: Technical description of the specific error detail.
          example: Invalid channel code
      description: Technical error detail indicating the source component, code, and specific description.

    DateTimeRecord:
      type: object
      properties:
        dateTimeContent:
          type: string
          description: The particular date and time point in the progression of time
          format: Text
        timeZoneCode:
          type: string
          description: The time zone to which the date time refers.
          format: Text
      description: ''
    Identifier:
      type: object
      properties:
        identifierValue:
          type: string
          description: 'tThe actual unique code or number (e.g., passport number, drivers license number).'
          format: Value
      description: An identifier that allows to uniquely refer to an instance of a Document.
    TransactionTypeValues:
      enum:
        - FinancialTransaction
        - BankingTransaction
      type: string
      description: >
        * `FinancialTransaction` - 
        * `BankingTransaction` -
    PaymentDateTimeTypeValues:
      enum:
        - RequestedExecutionDate
        - AcceptanceDate
      type: string
      description: >
        * `RequestedExecutionDate` - Date at which the initiating party requests the clearing agent to process the payment. ISO20022\nUsage: This is the date on which the debtor's account is to be debited. If payment by cheque, the date when the cheque must be generated by the bank. 
        * `AcceptanceDate` - Date and time at which all processing conditions for execution of the payment are met and adequate financial cover is available at the account servicing agent. ISO20022
    PaymentDateTime:
      type: object
      properties:
        paymentDate:
          $ref: '#/components/schemas/DateTimeRecord'
        paymentDateType:
          $ref: '#/components/schemas/PaymentDateTimeTypeValues'
      description: 'Key dates related to the payment. '
    CurrencyCode:
      type: object
      properties:
        accountCurrencyType:
          $ref: '#/components/schemas/CurrencyTypeValues'
      description: ''
    Amount:
      type: object
      properties:
        amountValue:
          type: string
          description: ''
          format: Value
        amountCurrency:
          $ref: '#/components/schemas/CurrencyCode'
      description: ''
    PaymentTypeValues:
      enum:
        - Cashtransaction
        - Loanrepayment
        - Taxpayment
        - Other
      type: string
      description: >
        * `Cashtransaction` - Transaction is a withdrawal/deposit of cash.
        * `Loanrepayment` - Transaction is an amount of money transferred in repayment of loan.
        * `Taxpayment` - Transaction is a payment of taxes.
        * `Other` - Specifies that a proprietary code must be indicated.
    PaymentIdentificationTypeValues:
      enum:
        - Transactionidentification
        - PaymentOrderID
      type: string
      description: >
        * `Transactionidentification` - Unique identification assigned by the first instructing agent to unambiguously identify the transaction and passed on, unchanged, throughout the entire interbank chain. (ISO20022)
        * `PaymentOrderID` - Internal unique identifier for the payment instruction, used within the bank’s systems to track the order from initiation through to execution.
    PaymentIdentification:
      type: object
      properties:
        paymentIdentification:
          $ref: '#/components/schemas/Identifier'
        paymentIdentificationType:
          $ref: '#/components/schemas/PaymentIdentificationTypeValues'
      description: ''
    PaymentTransactionStatusTypeValues:
      enum:
        - Received
        - Pending
        - Accepted
        - Paymentcancelled
      type: string
      description: >
        * `Received` - Payment initiation has been received by the receiving agent.
        * `Pending` - Payment initiation or individual transaction included in the payment initiation is pending.  Further checks and status update will be performed.
        * `Accepted` - Request is accepted.
        * `Paymentcancelled` - Payment is cancelled.
    PaymentTransactionStatus:
      type: object
      properties:
        paymentTransactionStatusType:
          $ref: '#/components/schemas/PaymentTransactionStatusTypeValues'
      description: "Specifies the status of a payment transaction at a specified time.\nElements"
    AccountIdentificationTypeValues:
      enum:
        - AccountNumber
        - PAN
      type: string
      description: >
        * `AccountNumber` - String of characters (mainly numbers) used to identify an account.(ISO20022)
        * `PAN` - Primary Account Number - identifier scheme used to identify a card account. (OBExternalAccountIdentification4Code)
    AccountIdentification:
      type: object
      properties:
        accountIdentificationType:
          $ref: '#/components/schemas/AccountIdentificationTypeValues'
        accountIdentification:
          $ref: '#/components/schemas/Identifier'
      description: The identifier of account like Account Number.
    Account:
      type: object
      properties:
        accountIdentification:
          $ref: '#/components/schemas/AccountIdentification'
      description: ''
    PaymentTransaction:
      type: object
      properties:
        paymentTransactionType:
          $ref: '#/components/schemas/PaymentTypeValues'
        paymentTransactionAmount:
          $ref: '#/components/schemas/Amount'
        transactionType:
          $ref: '#/components/schemas/TransactionTypeValues'
        financialTransactionFromAccount:
          $ref: '#/components/schemas/Account'
      description: The details of the payment transaction
    PaymentTransactionResponse:
      type: object
      properties:
        paymentTransactionIdentification:
          $ref: '#/components/schemas/PaymentIdentification'
        paymentTransactionDateTime:
          $ref: '#/components/schemas/PaymentDateTime'
        paymentTransactionStatus:
          $ref: '#/components/schemas/PaymentTransactionStatus'
      description: The details of the payment transaction
    Payer:
      type: object
      properties:
        partyIdentification:
          $ref: '#/components/schemas/PartyIdentification'
      description: Reference to the payer
    PaymentOrderInitiationTransaction:
      type: object
      properties:
        paymentTransactionType:
          $ref: '#/components/schemas/TransactionTypeValues'
        paymentTransaction:
          $ref: '#/components/schemas/PaymentTransaction'
        payerReference:
          $ref: '#/components/schemas/Payer'
      description: 'Execute a well-bounded financial transaction/task, typically involving largely automated/structured fulfillment processing within Payment Initiation. '
    PaymentOrderInitiationTransactionResponse:
      type: object
      properties:
        paymentTransactionType:
          $ref: '#/components/schemas/TransactionTypeValues'
        paymentTransaction:
          $ref: '#/components/schemas/PaymentTransactionResponse'
      description: 'Execute a well-bounded financial transaction/task, typically involving largely automated/structured fulfillment processing within Payment Initiation. '
    CurrencyTypeValues:
      enum:
        - PEN
        - USD
      type: string
      description: >
        * `USD` US Dollar - UNITED STATES OF AMERICA (THE)
        * `PEN` Sol - PERU
    PartyIdentificationTypeValues:
      enum:
        - Identitycardnumber
        - Nationalregistrationidentificationnumber
        - Registrationauthorityidentification
        - Passportnumber
      type: string
      description: >
        * `Identitycardnumber` - Number assigned by a national authority to an identity card.
        * `Nationalregistrationidentificationnumber` - National registration identification number. In Singapore this is known as the NRIC.
        * `Registrationauthorityidentification` - An identifier for the Legal Entity in a business registry in the jurisdiction of legal registration, or in the appropriate registration authority. (ISO20022)
        * `Passportnumber` - Number assigned by a passport authority.
    PartyIdentification:
      type: object
      properties:
        partyIdentificationType:
          $ref: '#/components/schemas/PartyIdentificationTypeValues'
        partyIdentification:
          $ref: '#/components/schemas/Identifier'
      description: ''
  responses:
    BadRequest:
      description: BadRequest
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ExceptionResponse'
    Unauthorized:
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ExceptionResponse'
    Forbidden:
      description: Forbidden
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ExceptionResponse'
    NotFound:
      description: NotFound
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ExceptionResponse'
    TooManyRequests:
      description: TooManyRequests
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ExceptionResponse'
    InternalServerError:
      description: InternalServerError
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ExceptionResponse'
    PaymentOrderInitiationTransaction:
      description: PaymentOrderInitiationTransaction
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/PaymentOrderInitiationTransactionResponse'
  requestBodies:
    PaymentOrderInitiationTransaction:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/PaymentOrderInitiationTransaction'
      required: true